#!/bin/sh

# debian-style init script for peervpn (http://peervpn.net)

# written 2012 by netzverweigerer <spampostfach1@yahoo.de>

# NOTES:
# $syslog removed from Should-Start section because peervpn does not have
# syslog functionality yet

### BEGIN INIT INFO
# Provides:          peervpn
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs $network
# Should-Start:      $named
# Should-Stop:       
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start peervpn daemon
# Description:       peervpn installation is assumed in "/opt/peervpn/"
#                    config file should just be named "peervpn.conf"
### END INIT INFO

DAEMON="/opt/peervpn/peervpn"
CONFIG="/opt/peervpn/peervpn.conf"
NAME="peervpn"
DESC="peervpn daemon"
PIDFILE="/var/run/peervpn.pid"

if [ ! -f $DAEMON ]; then
  echo "error: $DAEMON file does not exist."
  exit 1
fi

start() {
  echo "starting $DESC"
  start-stop-daemon -S -b -m -p "$PIDFILE" -N -5 --exec "$DAEMON" "$CONFIG"
}

stop() {
  echo "stopping $DESC"
  start-stop-daemon -K -p "$PIDFILE"
  sleep 0.5
  if [ -f "$PIDFILE" ]; then
    echo "removing $PIDFILE"
    rm -rfv "$PIDFILE"
  fi
}

restart() {
  stop
  sleep 0.5
  i=0;
  while [ -f $PIDFILE ] ; do
  if [ $i = '10' ] ; then
    echo "could not restart: $DESC"
    break
  else
    echo -n "."
    sleep 0.5
    i=$(($i+1))
  fi    
  done
  start
}

usage() {
  echo "Usage: /etc/init.d/$NAME {start|stop|restart}"
  exit 1
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart)
    echo -n "Restarting ${DESC}. "
    stop
    start
  ;;
  *)
    usage
  ;;
esac

echo

exit 0



